version: '3.8'
services:
    nginx:
        container_name: getCookie_nginx
        build:
            context: .
            dockerfile: ./docker/nginx.Dockerfile
        ports:
            - "7865:80"
            - "7866:443"
        volumes:
            - ./src:/usr/share/nginx/html
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./log/error.log:/var/log/nginx/error.log
            - ./log/access.log:/var/log/nginx/access.log
        restart: always
        networks:
            - internal
    php-fpm:
        image: ngnisp/getcookie_php
        # volumes:
        #     - ./src:/usr/share/nginx/html
        networks:
            - internal
    db:
        container_name: getCookie_db
        image: mariadb:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root@root
            MYSQL_USER: ngn
            MYSQL_PASSWORD: ngn@ngn
            MYSQL_DATABASE: GetCookie
        volumes:
            - ./db:/var/lib/mysql/
        networks:
            - internal
networks:
    internal:
        driver: bridge